version: "3.7"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: always

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 1

    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-enterprise-kafka:7.6.1
    restart: always

    depends_on:
      - zookeeper

    ports:
      - 29092:29092

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      JMX_PORT: "9999"

    volumes:
      - kafka-data:/var/lib/kafka/data

  debezium:
    image: debezium/connect:2.6.1.Final
    restart: always

    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      DATABASE_HISTORY: io.debezium.relational.history.KafkaDatabaseHistory
      DATABASE_HISTORY_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_HISTORY_TOPIC: debezium_history
      CONNECT_PRODUCER_RETRIES: 20
      CONNECT_PRODUCER_RETRY_BACKOFF_MS: 1000
      KAFKA_CLIENT_ID: debezium-connect
      KAFKA_PRODUCER_CLIENT_ID: debezium-connect-producer
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      CONNECT_REST_ADVERTISED_PORT: 8083
      TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS: 5000
      
    depends_on: 
      - kafka
    ports:
      - 8083:8083
    volumes:
      - debezium-data:/debezium/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    restart: always

    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081,http://localhost:8081
      SCHEMA_REGISTRY_GROUP_ID: 1
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: backward

    ports:
      - 8081:8081

    depends_on: [zookeeper, kafka]

    volumes:
      - schema-registry-data:/var/lib/schema-registry/data

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    restart: always

    ports:
      - "9000:9000"

    depends_on:
      - zookeeper
      - kafka

    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

    command: -Dpidfile.path=/dev/null
    
volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  debezium-data:
  schema-registry-data: